.\" Manpage for gh.
.\" Contact pdq@localhost
.TH man 8 "December 02 2012" "0.1" "gh man page"
.SH NAME
gh \- github command line tool for mooOS and Arch Linux
.SH SYNOPSIS
gh [-{b|V|q}][-{c|r|s|m}] [user/{repo|submodule}|message]
.SH DESCRIPTION
gh is a shell program, a github command line tool for Arch Linux, using git and hub packages.
.SH OPTIONS
.
.br
-V print version number
.
.br
-b backup [-b]
.
.br
-m backup commit message [-m]
.
.br
-c clone github repo [-c user/repo]
.
.br
-r create github repo [-r user/repo]
.
.br
-s create submodule [-s user/submodule -r /user/repo]
.
.br
-h help
.
.br
-q quiet
.
.br
.SH SEE ALSO
git(1), hub(1)
.SH BUGS
No known bugs.
.SH AUTHOR
pdq (pdq@hush.com)